// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_log.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_log (actor_user_id, actor_ip, action, target_type, target_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_user_id, actor_ip, action, target_type, target_id, payload, created_at
`

type CreateAuditEventParams struct {
	ActorUserID pgtype.Int8
	ActorIp     *netip.Addr
	Action      string
	TargetType  pgtype.Text
	TargetID    pgtype.Int8
	Payload     []byte
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ActorUserID,
		arg.ActorIp,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorIp,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditByActor = `-- name: ListAuditByActor :many
SELECT id, actor_user_id, actor_ip, action, target_type, target_id, payload, created_at
  FROM audit_log
 WHERE actor_user_id = $1
 ORDER BY id DESC
 LIMIT $2
`

type ListAuditByActorParams struct {
	ActorUserID pgtype.Int8
	Limit       int32
}

func (q *Queries) ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByActor, arg.ActorUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorIp,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTarget = `-- name: ListAuditByTarget :many
SELECT id, actor_user_id, actor_ip, action, target_type, target_id, payload, created_at
  FROM audit_log
 WHERE target_type = $1
   AND target_id   = $2
 ORDER BY id DESC
 LIMIT $3
`

type ListAuditByTargetParams struct {
	TargetType pgtype.Text
	TargetID   pgtype.Int8
	Limit      int32
}

func (q *Queries) ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTarget, arg.TargetType, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorIp,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
