// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deploys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendDeployOutput = `-- name: AppendDeployOutput :exec
UPDATE deploys
   SET output_log = output_log || $2
 WHERE id = $1
`

type AppendDeployOutputParams struct {
	ID        int64
	OutputLog string
}

func (q *Queries) AppendDeployOutput(ctx context.Context, arg AppendDeployOutputParams) error {
	_, err := q.db.Exec(ctx, appendDeployOutput, arg.ID, arg.OutputLog)
	return err
}

const createDeploy = `-- name: CreateDeploy :one
INSERT INTO deploys (site_id, trigger, triggered_by)
VALUES ($1, $2, $3)
RETURNING id, site_id, trigger, status, started_at, finished_at, exit_code, output_log, triggered_by, created_at
`

type CreateDeployParams struct {
	SiteID      int64
	Trigger     string
	TriggeredBy pgtype.Int8
}

func (q *Queries) CreateDeploy(ctx context.Context, arg CreateDeployParams) (Deploy, error) {
	row := q.db.QueryRow(ctx, createDeploy, arg.SiteID, arg.Trigger, arg.TriggeredBy)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Trigger,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.OutputLog,
		&i.TriggeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploy = `-- name: GetDeploy :one
SELECT id, site_id, trigger, status, started_at, finished_at, exit_code, output_log, triggered_by, created_at FROM deploys WHERE id = $1
`

func (q *Queries) GetDeploy(ctx context.Context, id int64) (Deploy, error) {
	row := q.db.QueryRow(ctx, getDeploy, id)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Trigger,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.OutputLog,
		&i.TriggeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploysForSite = `-- name: ListDeploysForSite :many
SELECT id, site_id, trigger, status, started_at, finished_at, exit_code, output_log, triggered_by, created_at
  FROM deploys
 WHERE site_id = $1
 ORDER BY id DESC
 LIMIT $2
`

type ListDeploysForSiteParams struct {
	SiteID int64
	Limit  int32
}

func (q *Queries) ListDeploysForSite(ctx context.Context, arg ListDeploysForSiteParams) ([]Deploy, error) {
	rows, err := q.db.Query(ctx, listDeploysForSite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deploy
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Trigger,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.OutputLog,
			&i.TriggeredBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeployFinished = `-- name: MarkDeployFinished :exec
UPDATE deploys
   SET status      = $2,
       exit_code   = $3,
       finished_at = now()
 WHERE id = $1
`

type MarkDeployFinishedParams struct {
	ID       int64
	Status   string
	ExitCode pgtype.Int4
}

func (q *Queries) MarkDeployFinished(ctx context.Context, arg MarkDeployFinishedParams) error {
	_, err := q.db.Exec(ctx, markDeployFinished, arg.ID, arg.Status, arg.ExitCode)
	return err
}

const markDeployRunning = `-- name: MarkDeployRunning :exec
UPDATE deploys
   SET status     = 'running',
       started_at = now()
 WHERE id = $1
`

func (q *Queries) MarkDeployRunning(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markDeployRunning, id)
	return err
}
