// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deploy_scripts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeployScript = `-- name: GetDeployScript :one
SELECT site_id, body, cron_spec, updated_at FROM site_deploy_scripts WHERE site_id = $1
`

func (q *Queries) GetDeployScript(ctx context.Context, siteID int64) (SiteDeployScript, error) {
	row := q.db.QueryRow(ctx, getDeployScript, siteID)
	var i SiteDeployScript
	err := row.Scan(
		&i.SiteID,
		&i.Body,
		&i.CronSpec,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeployScriptVersion = `-- name: InsertDeployScriptVersion :exec
INSERT INTO site_deploy_script_versions (site_id, body, saved_by)
VALUES ($1, $2, $3)
`

type InsertDeployScriptVersionParams struct {
	SiteID  int64
	Body    string
	SavedBy pgtype.Int8
}

func (q *Queries) InsertDeployScriptVersion(ctx context.Context, arg InsertDeployScriptVersionParams) error {
	_, err := q.db.Exec(ctx, insertDeployScriptVersion, arg.SiteID, arg.Body, arg.SavedBy)
	return err
}

const listDeployScriptVersions = `-- name: ListDeployScriptVersions :many
SELECT id, site_id, body, saved_at, saved_by
  FROM site_deploy_script_versions
 WHERE site_id = $1
 ORDER BY saved_at DESC
 LIMIT $2
`

type ListDeployScriptVersionsParams struct {
	SiteID int64
	Limit  int32
}

func (q *Queries) ListDeployScriptVersions(ctx context.Context, arg ListDeployScriptVersionsParams) ([]SiteDeployScriptVersion, error) {
	rows, err := q.db.Query(ctx, listDeployScriptVersions, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteDeployScriptVersion
	for rows.Next() {
		var i SiteDeployScriptVersion
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Body,
			&i.SavedAt,
			&i.SavedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledDeployScripts = `-- name: ListScheduledDeployScripts :many
SELECT site_id, cron_spec
  FROM site_deploy_scripts
 WHERE cron_spec IS NOT NULL
   AND cron_spec <> ''
 ORDER BY site_id
`

type ListScheduledDeployScriptsRow struct {
	SiteID   int64
	CronSpec pgtype.Text
}

func (q *Queries) ListScheduledDeployScripts(ctx context.Context) ([]ListScheduledDeployScriptsRow, error) {
	rows, err := q.db.Query(ctx, listScheduledDeployScripts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledDeployScriptsRow
	for rows.Next() {
		var i ListScheduledDeployScriptsRow
		if err := rows.Scan(&i.SiteID, &i.CronSpec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeployScript = `-- name: UpsertDeployScript :one
INSERT INTO site_deploy_scripts (site_id, body, cron_spec)
VALUES ($1, $2, $3)
ON CONFLICT (site_id)
DO UPDATE SET
    body       = EXCLUDED.body,
    cron_spec  = EXCLUDED.cron_spec,
    updated_at = now()
RETURNING site_id, body, cron_spec, updated_at
`

type UpsertDeployScriptParams struct {
	SiteID   int64
	Body     string
	CronSpec pgtype.Text
}

func (q *Queries) UpsertDeployScript(ctx context.Context, arg UpsertDeployScriptParams) (SiteDeployScript, error) {
	row := q.db.QueryRow(ctx, upsertDeployScript, arg.SiteID, arg.Body, arg.CronSpec)
	var i SiteDeployScript
	err := row.Scan(
		&i.SiteID,
		&i.Body,
		&i.CronSpec,
		&i.UpdatedAt,
	)
	return i, err
}
