// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64
	ActorUserID pgtype.Int8
	ActorIp     *netip.Addr
	Action      string
	TargetType  pgtype.Text
	TargetID    pgtype.Int8
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

type Deploy struct {
	ID          int64
	SiteID      int64
	Trigger     string
	Status      string
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	ExitCode    pgtype.Int4
	OutputLog   string
	TriggeredBy pgtype.Int8
	CreatedAt   pgtype.Timestamptz
}

type Server struct {
	ID               int64
	Name             string
	PublicIp         netip.Addr
	SshUser          string
	AgentFingerprint pgtype.Text
	AgentLastSeen    pgtype.Timestamptz
	ProvisionStatus  string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ProvisionError   pgtype.Text
}

type Session struct {
	ID          pgtype.UUID
	UserID      int64
	IssuedAt    pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RefreshedAt pgtype.Timestamptz
	Ip          *netip.Addr
	UserAgent   pgtype.Text
}

type Site struct {
	ID              int64
	ServerID        int64
	Name            string
	Domain          string
	SiteType        string
	ProvisionStatus string
	ProvisionError  pgtype.Text
	WorkingDir      string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	WebhookSecret   pgtype.Text
}

type SiteDeployScript struct {
	SiteID    int64
	Body      string
	CronSpec  pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

type SiteDeployScriptVersion struct {
	ID      int64
	SiteID  int64
	Body    string
	SavedAt pgtype.Timestamptz
	SavedBy pgtype.Int8
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Role         string
	Enabled      bool
	MfaSecret    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
