// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AppendDeployOutput(ctx context.Context, arg AppendDeployOutputParams) error
	ClearServerProvisionError(ctx context.Context, id int64) error
	ClearSiteProvisionError(ctx context.Context, id int64) error
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditLog, error)
	CreateDeploy(ctx context.Context, arg CreateDeployParams) (Deploy, error)
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateSiteCert(ctx context.Context, arg CreateSiteCertParams) (SiteCert, error)
	CreateSiteDaemon(ctx context.Context, arg CreateSiteDaemonParams) (SiteDaemon, error)
	CreateSiteDatabase(ctx context.Context, arg CreateSiteDatabaseParams) (SiteDatabase, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteServer(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionsForUser(ctx context.Context, userID int64) error
	DeleteSite(ctx context.Context, id int64) error
	DeleteSiteCert(ctx context.Context, id int64) error
	DeleteSiteDaemon(ctx context.Context, id int64) error
	DeleteSiteDatabase(ctx context.Context, id int64) error
	DeleteSitePermission(ctx context.Context, arg DeleteSitePermissionParams) error
	DeleteTeam(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetDeploy(ctx context.Context, id int64) (Deploy, error)
	GetDeployScript(ctx context.Context, siteID int64) (SiteDeployScript, error)
	GetServer(ctx context.Context, id int64) (Server, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSite(ctx context.Context, id int64) (Site, error)
	GetSiteCert(ctx context.Context, id int64) (SiteCert, error)
	GetSiteCertByDomain(ctx context.Context, arg GetSiteCertByDomainParams) (SiteCert, error)
	GetSiteCompose(ctx context.Context, siteID int64) (SiteCompose, error)
	GetSiteDaemon(ctx context.Context, id int64) (SiteDaemon, error)
	GetSiteDatabase(ctx context.Context, id int64) (SiteDatabase, error)
	GetSiteWebhookSecret(ctx context.Context, id int64) (pgtype.Text, error)
	GetTeam(ctx context.Context, id int64) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	InsertDeployScriptVersion(ctx context.Context, arg InsertDeployScriptVersionParams) error
	ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error)
	ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error)
	ListDeployScriptVersions(ctx context.Context, arg ListDeployScriptVersionsParams) ([]SiteDeployScriptVersion, error)
	ListDeploysForSite(ctx context.Context, arg ListDeploysForSiteParams) ([]Deploy, error)
	ListScheduledDeployScripts(ctx context.Context) ([]ListScheduledDeployScriptsRow, error)
	ListServers(ctx context.Context) ([]Server, error)
	ListSiteCertsForSite(ctx context.Context, siteID int64) ([]SiteCert, error)
	ListSiteDaemonsForSite(ctx context.Context, siteID int64) ([]SiteDaemon, error)
	ListSiteDatabasesForSite(ctx context.Context, siteID int64) ([]SiteDatabase, error)
	ListSitePermissions(ctx context.Context, siteID int64) ([]SitePermission, error)
	ListSites(ctx context.Context) ([]Site, error)
	ListSitesByServer(ctx context.Context, serverID int64) ([]Site, error)
	ListTeamMembers(ctx context.Context, teamID int64) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListTeamsForUser(ctx context.Context, userID int64) ([]Team, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkDeployFinished(ctx context.Context, arg MarkDeployFinishedParams) error
	MarkDeployRunning(ctx context.Context, id int64) error
	RefreshSession(ctx context.Context, arg RefreshSessionParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	SetServerAgentFingerprint(ctx context.Context, arg SetServerAgentFingerprintParams) error
	SetServerProvisionError(ctx context.Context, arg SetServerProvisionErrorParams) error
	SetServerStatus(ctx context.Context, arg SetServerStatusParams) error
	SetSiteCertError(ctx context.Context, arg SetSiteCertErrorParams) error
	SetSiteCertIssued(ctx context.Context, arg SetSiteCertIssuedParams) error
	SetSiteCertStatus(ctx context.Context, arg SetSiteCertStatusParams) error
	SetSiteDatabaseStatus(ctx context.Context, arg SetSiteDatabaseStatusParams) error
	SetSiteProvisionError(ctx context.Context, arg SetSiteProvisionErrorParams) error
	SetSiteProxyPort(ctx context.Context, arg SetSiteProxyPortParams) error
	SetSiteStatus(ctx context.Context, arg SetSiteStatusParams) error
	SetSiteWebhookSecret(ctx context.Context, arg SetSiteWebhookSecretParams) error
	SetSiteWorkingDir(ctx context.Context, arg SetSiteWorkingDirParams) error
	SetUserEnabled(ctx context.Context, arg SetUserEnabledParams) error
	SetUserMFASecret(ctx context.Context, arg SetUserMFASecretParams) error
	// Returns the union of direct user perms + team-mediated perms a
	// user holds for a site. Aggregated (OR-ed) at the SQL layer.
	// BOOL_OR over zero rows yields NULL — COALESCE to false so the
	// "no permissions" case comes back as an all-false row.
	SitePermissionsForUser(ctx context.Context, arg SitePermissionsForUserParams) (SitePermissionsForUserRow, error)
	TouchServerAgent(ctx context.Context, id int64) error
	TouchSiteDatabaseBackup(ctx context.Context, id int64) error
	UpdateSiteDaemonStatus(ctx context.Context, arg UpdateSiteDaemonStatusParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertDeployScript(ctx context.Context, arg UpsertDeployScriptParams) (SiteDeployScript, error)
	UpsertSiteCompose(ctx context.Context, arg UpsertSiteComposeParams) (SiteCompose, error)
	UpsertSiteTeamPermission(ctx context.Context, arg UpsertSiteTeamPermissionParams) (SitePermission, error)
	UpsertSiteUserPermission(ctx context.Context, arg UpsertSiteUserPermissionParams) (SitePermission, error)
}

var _ Querier = (*Queries)(nil)
