// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearServerProvisionError(ctx context.Context, id int64) error
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditLog, error)
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteServer(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionsForUser(ctx context.Context, userID int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetServer(ctx context.Context, id int64) (Server, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error)
	ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error)
	ListServers(ctx context.Context) ([]Server, error)
	ListUsers(ctx context.Context) ([]User, error)
	RefreshSession(ctx context.Context, arg RefreshSessionParams) error
	SetServerAgentFingerprint(ctx context.Context, arg SetServerAgentFingerprintParams) error
	SetServerProvisionError(ctx context.Context, arg SetServerProvisionErrorParams) error
	SetServerStatus(ctx context.Context, arg SetServerStatusParams) error
	SetUserEnabled(ctx context.Context, arg SetUserEnabledParams) error
	SetUserMFASecret(ctx context.Context, arg SetUserMFASecretParams) error
	TouchServerAgent(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
