// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: servers.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearServerProvisionError = `-- name: ClearServerProvisionError :exec
UPDATE servers
   SET provision_error = NULL,
       updated_at      = now()
 WHERE id = $1
`

func (q *Queries) ClearServerProvisionError(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearServerProvisionError, id)
	return err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers (name, public_ip, ssh_user, provision_status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, public_ip, ssh_user, agent_fingerprint, agent_last_seen, provision_status, created_at, updated_at, provision_error
`

type CreateServerParams struct {
	Name            string
	PublicIp        netip.Addr
	SshUser         string
	ProvisionStatus string
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.Name,
		arg.PublicIp,
		arg.SshUser,
		arg.ProvisionStatus,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicIp,
		&i.SshUser,
		&i.AgentFingerprint,
		&i.AgentLastSeen,
		&i.ProvisionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisionError,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const getServer = `-- name: GetServer :one
SELECT id, name, public_ip, ssh_user, agent_fingerprint, agent_last_seen, provision_status, created_at, updated_at, provision_error FROM servers WHERE id = $1
`

func (q *Queries) GetServer(ctx context.Context, id int64) (Server, error) {
	row := q.db.QueryRow(ctx, getServer, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicIp,
		&i.SshUser,
		&i.AgentFingerprint,
		&i.AgentLastSeen,
		&i.ProvisionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProvisionError,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT id, name, public_ip, ssh_user, agent_fingerprint, agent_last_seen, provision_status, created_at, updated_at, provision_error FROM servers ORDER BY id
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicIp,
			&i.SshUser,
			&i.AgentFingerprint,
			&i.AgentLastSeen,
			&i.ProvisionStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProvisionError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServerAgentFingerprint = `-- name: SetServerAgentFingerprint :exec
UPDATE servers
   SET agent_fingerprint = $2,
       updated_at        = now()
 WHERE id = $1
`

type SetServerAgentFingerprintParams struct {
	ID               int64
	AgentFingerprint pgtype.Text
}

func (q *Queries) SetServerAgentFingerprint(ctx context.Context, arg SetServerAgentFingerprintParams) error {
	_, err := q.db.Exec(ctx, setServerAgentFingerprint, arg.ID, arg.AgentFingerprint)
	return err
}

const setServerProvisionError = `-- name: SetServerProvisionError :exec
UPDATE servers
   SET provision_status = 'error',
       provision_error  = $2,
       updated_at       = now()
 WHERE id = $1
`

type SetServerProvisionErrorParams struct {
	ID             int64
	ProvisionError pgtype.Text
}

func (q *Queries) SetServerProvisionError(ctx context.Context, arg SetServerProvisionErrorParams) error {
	_, err := q.db.Exec(ctx, setServerProvisionError, arg.ID, arg.ProvisionError)
	return err
}

const setServerStatus = `-- name: SetServerStatus :exec
UPDATE servers
   SET provision_status = $2,
       updated_at       = now()
 WHERE id = $1
`

type SetServerStatusParams struct {
	ID              int64
	ProvisionStatus string
}

func (q *Queries) SetServerStatus(ctx context.Context, arg SetServerStatusParams) error {
	_, err := q.db.Exec(ctx, setServerStatus, arg.ID, arg.ProvisionStatus)
	return err
}

const touchServerAgent = `-- name: TouchServerAgent :exec
UPDATE servers
   SET agent_last_seen = now(),
       updated_at      = now()
 WHERE id = $1
`

func (q *Queries) TouchServerAgent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchServerAgent, id)
	return err
}
