// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at, ip, user_agent)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, user_id, issued_at, expires_at, refreshed_at, ip, user_agent
`

type CreateSessionParams struct {
	UserID    int64
	ExpiresAt pgtype.Timestamptz
	Ip        *netip.Addr
	UserAgent pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RefreshedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, issued_at, expires_at, refreshed_at, ip, user_agent FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RefreshedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const refreshSession = `-- name: RefreshSession :exec
UPDATE sessions
   SET refreshed_at = now(),
       expires_at   = $2
 WHERE id = $1
`

type RefreshSessionParams struct {
	ID        pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) error {
	_, err := q.db.Exec(ctx, refreshSession, arg.ID, arg.ExpiresAt)
	return err
}
