// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: site_compose.sql

package sqlc

import (
	"context"
)

const getSiteCompose = `-- name: GetSiteCompose :one
SELECT site_id, body, updated_at FROM site_compose WHERE site_id = $1
`

func (q *Queries) GetSiteCompose(ctx context.Context, siteID int64) (SiteCompose, error) {
	row := q.db.QueryRow(ctx, getSiteCompose, siteID)
	var i SiteCompose
	err := row.Scan(&i.SiteID, &i.Body, &i.UpdatedAt)
	return i, err
}

const upsertSiteCompose = `-- name: UpsertSiteCompose :one
INSERT INTO site_compose (site_id, body)
VALUES ($1, $2)
ON CONFLICT (site_id)
DO UPDATE SET
    body       = EXCLUDED.body,
    updated_at = now()
RETURNING site_id, body, updated_at
`

type UpsertSiteComposeParams struct {
	SiteID int64
	Body   string
}

func (q *Queries) UpsertSiteCompose(ctx context.Context, arg UpsertSiteComposeParams) (SiteCompose, error) {
	row := q.db.QueryRow(ctx, upsertSiteCompose, arg.SiteID, arg.Body)
	var i SiteCompose
	err := row.Scan(&i.SiteID, &i.Body, &i.UpdatedAt)
	return i, err
}
