// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: site_daemons.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSiteDaemon = `-- name: CreateSiteDaemon :one
INSERT INTO site_daemons (site_id, slug, name, command, auto_restart)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, site_id, slug, name, command, auto_restart, status, last_action_at, last_error, created_at, updated_at
`

type CreateSiteDaemonParams struct {
	SiteID      int64
	Slug        string
	Name        string
	Command     string
	AutoRestart bool
}

func (q *Queries) CreateSiteDaemon(ctx context.Context, arg CreateSiteDaemonParams) (SiteDaemon, error) {
	row := q.db.QueryRow(ctx, createSiteDaemon,
		arg.SiteID,
		arg.Slug,
		arg.Name,
		arg.Command,
		arg.AutoRestart,
	)
	var i SiteDaemon
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Slug,
		&i.Name,
		&i.Command,
		&i.AutoRestart,
		&i.Status,
		&i.LastActionAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSiteDaemon = `-- name: DeleteSiteDaemon :exec
DELETE FROM site_daemons WHERE id = $1
`

func (q *Queries) DeleteSiteDaemon(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSiteDaemon, id)
	return err
}

const getSiteDaemon = `-- name: GetSiteDaemon :one
SELECT id, site_id, slug, name, command, auto_restart, status, last_action_at, last_error, created_at, updated_at FROM site_daemons WHERE id = $1
`

func (q *Queries) GetSiteDaemon(ctx context.Context, id int64) (SiteDaemon, error) {
	row := q.db.QueryRow(ctx, getSiteDaemon, id)
	var i SiteDaemon
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Slug,
		&i.Name,
		&i.Command,
		&i.AutoRestart,
		&i.Status,
		&i.LastActionAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSiteDaemonsForSite = `-- name: ListSiteDaemonsForSite :many
SELECT id, site_id, slug, name, command, auto_restart, status, last_action_at, last_error, created_at, updated_at FROM site_daemons WHERE site_id = $1 ORDER BY id DESC
`

func (q *Queries) ListSiteDaemonsForSite(ctx context.Context, siteID int64) ([]SiteDaemon, error) {
	rows, err := q.db.Query(ctx, listSiteDaemonsForSite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteDaemon
	for rows.Next() {
		var i SiteDaemon
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Slug,
			&i.Name,
			&i.Command,
			&i.AutoRestart,
			&i.Status,
			&i.LastActionAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteDaemonStatus = `-- name: UpdateSiteDaemonStatus :exec
UPDATE site_daemons
   SET status         = $2,
       last_action_at = now(),
       last_error     = $3,
       updated_at     = now()
 WHERE id = $1
`

type UpdateSiteDaemonStatusParams struct {
	ID        int64
	Status    string
	LastError pgtype.Text
}

func (q *Queries) UpdateSiteDaemonStatus(ctx context.Context, arg UpdateSiteDaemonStatusParams) error {
	_, err := q.db.Exec(ctx, updateSiteDaemonStatus, arg.ID, arg.Status, arg.LastError)
	return err
}
