// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: site_databases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSiteDatabase = `-- name: CreateSiteDatabase :one
INSERT INTO site_databases (site_id, engine, name, username, password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, site_id, engine, name, username, password, status, last_error, last_backup_at, created_at, updated_at
`

type CreateSiteDatabaseParams struct {
	SiteID   int64
	Engine   string
	Name     string
	Username string
	Password string
}

func (q *Queries) CreateSiteDatabase(ctx context.Context, arg CreateSiteDatabaseParams) (SiteDatabase, error) {
	row := q.db.QueryRow(ctx, createSiteDatabase,
		arg.SiteID,
		arg.Engine,
		arg.Name,
		arg.Username,
		arg.Password,
	)
	var i SiteDatabase
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Engine,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.LastError,
		&i.LastBackupAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSiteDatabase = `-- name: DeleteSiteDatabase :exec
DELETE FROM site_databases WHERE id = $1
`

func (q *Queries) DeleteSiteDatabase(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSiteDatabase, id)
	return err
}

const getSiteDatabase = `-- name: GetSiteDatabase :one
SELECT id, site_id, engine, name, username, password, status, last_error, last_backup_at, created_at, updated_at FROM site_databases WHERE id = $1
`

func (q *Queries) GetSiteDatabase(ctx context.Context, id int64) (SiteDatabase, error) {
	row := q.db.QueryRow(ctx, getSiteDatabase, id)
	var i SiteDatabase
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Engine,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.LastError,
		&i.LastBackupAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSiteDatabasesForSite = `-- name: ListSiteDatabasesForSite :many
SELECT id, site_id, engine, name, username, password, status, last_error, last_backup_at, created_at, updated_at FROM site_databases WHERE site_id = $1 ORDER BY id DESC
`

func (q *Queries) ListSiteDatabasesForSite(ctx context.Context, siteID int64) ([]SiteDatabase, error) {
	rows, err := q.db.Query(ctx, listSiteDatabasesForSite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteDatabase
	for rows.Next() {
		var i SiteDatabase
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Engine,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.Status,
			&i.LastError,
			&i.LastBackupAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSiteDatabaseStatus = `-- name: SetSiteDatabaseStatus :exec
UPDATE site_databases
   SET status     = $2,
       last_error = $3,
       updated_at = now()
 WHERE id = $1
`

type SetSiteDatabaseStatusParams struct {
	ID        int64
	Status    string
	LastError pgtype.Text
}

func (q *Queries) SetSiteDatabaseStatus(ctx context.Context, arg SetSiteDatabaseStatusParams) error {
	_, err := q.db.Exec(ctx, setSiteDatabaseStatus, arg.ID, arg.Status, arg.LastError)
	return err
}

const touchSiteDatabaseBackup = `-- name: TouchSiteDatabaseBackup :exec
UPDATE site_databases
   SET last_backup_at = now(),
       updated_at     = now()
 WHERE id = $1
`

func (q *Queries) TouchSiteDatabaseBackup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchSiteDatabaseBackup, id)
	return err
}
