// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: site_certs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSiteCert = `-- name: CreateSiteCert :one
INSERT INTO site_certs (site_id, domain, status)
VALUES ($1, $2, 'pending')
ON CONFLICT (site_id, domain)
DO UPDATE SET
    status     = 'pending',
    last_error = NULL,
    updated_at = now()
RETURNING id, site_id, domain, status, issued_at, expires_at, last_error, created_at, updated_at
`

type CreateSiteCertParams struct {
	SiteID int64
	Domain string
}

func (q *Queries) CreateSiteCert(ctx context.Context, arg CreateSiteCertParams) (SiteCert, error) {
	row := q.db.QueryRow(ctx, createSiteCert, arg.SiteID, arg.Domain)
	var i SiteCert
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Domain,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSiteCert = `-- name: DeleteSiteCert :exec
DELETE FROM site_certs WHERE id = $1
`

func (q *Queries) DeleteSiteCert(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSiteCert, id)
	return err
}

const getSiteCert = `-- name: GetSiteCert :one
SELECT id, site_id, domain, status, issued_at, expires_at, last_error, created_at, updated_at FROM site_certs WHERE id = $1
`

func (q *Queries) GetSiteCert(ctx context.Context, id int64) (SiteCert, error) {
	row := q.db.QueryRow(ctx, getSiteCert, id)
	var i SiteCert
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Domain,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteCertByDomain = `-- name: GetSiteCertByDomain :one
SELECT id, site_id, domain, status, issued_at, expires_at, last_error, created_at, updated_at FROM site_certs WHERE site_id = $1 AND domain = $2
`

type GetSiteCertByDomainParams struct {
	SiteID int64
	Domain string
}

func (q *Queries) GetSiteCertByDomain(ctx context.Context, arg GetSiteCertByDomainParams) (SiteCert, error) {
	row := q.db.QueryRow(ctx, getSiteCertByDomain, arg.SiteID, arg.Domain)
	var i SiteCert
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Domain,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSiteCertsForSite = `-- name: ListSiteCertsForSite :many
SELECT id, site_id, domain, status, issued_at, expires_at, last_error, created_at, updated_at FROM site_certs WHERE site_id = $1 ORDER BY id DESC
`

func (q *Queries) ListSiteCertsForSite(ctx context.Context, siteID int64) ([]SiteCert, error) {
	rows, err := q.db.Query(ctx, listSiteCertsForSite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteCert
	for rows.Next() {
		var i SiteCert
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Domain,
			&i.Status,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSiteCertError = `-- name: SetSiteCertError :exec
UPDATE site_certs
   SET status     = 'error',
       last_error = $2,
       updated_at = now()
 WHERE id = $1
`

type SetSiteCertErrorParams struct {
	ID        int64
	LastError pgtype.Text
}

func (q *Queries) SetSiteCertError(ctx context.Context, arg SetSiteCertErrorParams) error {
	_, err := q.db.Exec(ctx, setSiteCertError, arg.ID, arg.LastError)
	return err
}

const setSiteCertIssued = `-- name: SetSiteCertIssued :exec
UPDATE site_certs
   SET status     = 'active',
       issued_at  = now(),
       expires_at = $2,
       last_error = NULL,
       updated_at = now()
 WHERE id = $1
`

type SetSiteCertIssuedParams struct {
	ID        int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SetSiteCertIssued(ctx context.Context, arg SetSiteCertIssuedParams) error {
	_, err := q.db.Exec(ctx, setSiteCertIssued, arg.ID, arg.ExpiresAt)
	return err
}

const setSiteCertStatus = `-- name: SetSiteCertStatus :exec
UPDATE site_certs
   SET status     = $2,
       updated_at = now()
 WHERE id = $1
`

type SetSiteCertStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) SetSiteCertStatus(ctx context.Context, arg SetSiteCertStatusParams) error {
	_, err := q.db.Exec(ctx, setSiteCertStatus, arg.ID, arg.Status)
	return err
}
