// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSiteProvisionError = `-- name: ClearSiteProvisionError :exec
UPDATE sites
   SET provision_error = NULL,
       updated_at      = now()
 WHERE id = $1
`

func (q *Queries) ClearSiteProvisionError(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearSiteProvisionError, id)
	return err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (server_id, name, domain, site_type, working_dir, provision_status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, server_id, name, domain, site_type, provision_status, provision_error, working_dir, created_at, updated_at, webhook_secret, proxy_port
`

type CreateSiteParams struct {
	ServerID   int64
	Name       string
	Domain     string
	SiteType   string
	WorkingDir string
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.ServerID,
		arg.Name,
		arg.Domain,
		arg.SiteType,
		arg.WorkingDir,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Domain,
		&i.SiteType,
		&i.ProvisionStatus,
		&i.ProvisionError,
		&i.WorkingDir,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
		&i.ProxyPort,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = $1
`

func (q *Queries) DeleteSite(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSite, id)
	return err
}

const getSite = `-- name: GetSite :one
SELECT id, server_id, name, domain, site_type, provision_status, provision_error, working_dir, created_at, updated_at, webhook_secret, proxy_port FROM sites WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Domain,
		&i.SiteType,
		&i.ProvisionStatus,
		&i.ProvisionError,
		&i.WorkingDir,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookSecret,
		&i.ProxyPort,
	)
	return i, err
}

const getSiteWebhookSecret = `-- name: GetSiteWebhookSecret :one
SELECT webhook_secret FROM sites WHERE id = $1
`

func (q *Queries) GetSiteWebhookSecret(ctx context.Context, id int64) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getSiteWebhookSecret, id)
	var webhook_secret pgtype.Text
	err := row.Scan(&webhook_secret)
	return webhook_secret, err
}

const listSites = `-- name: ListSites :many
SELECT id, server_id, name, domain, site_type, provision_status, provision_error, working_dir, created_at, updated_at, webhook_secret, proxy_port FROM sites ORDER BY id DESC
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Domain,
			&i.SiteType,
			&i.ProvisionStatus,
			&i.ProvisionError,
			&i.WorkingDir,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebhookSecret,
			&i.ProxyPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesByServer = `-- name: ListSitesByServer :many
SELECT id, server_id, name, domain, site_type, provision_status, provision_error, working_dir, created_at, updated_at, webhook_secret, proxy_port FROM sites WHERE server_id = $1 ORDER BY id DESC
`

func (q *Queries) ListSitesByServer(ctx context.Context, serverID int64) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSitesByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Domain,
			&i.SiteType,
			&i.ProvisionStatus,
			&i.ProvisionError,
			&i.WorkingDir,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebhookSecret,
			&i.ProxyPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSiteProvisionError = `-- name: SetSiteProvisionError :exec
UPDATE sites
   SET provision_status = 'error',
       provision_error  = $2,
       updated_at       = now()
 WHERE id = $1
`

type SetSiteProvisionErrorParams struct {
	ID             int64
	ProvisionError pgtype.Text
}

func (q *Queries) SetSiteProvisionError(ctx context.Context, arg SetSiteProvisionErrorParams) error {
	_, err := q.db.Exec(ctx, setSiteProvisionError, arg.ID, arg.ProvisionError)
	return err
}

const setSiteProxyPort = `-- name: SetSiteProxyPort :exec
UPDATE sites
   SET proxy_port = $2,
       updated_at = now()
 WHERE id = $1
`

type SetSiteProxyPortParams struct {
	ID        int64
	ProxyPort pgtype.Int4
}

func (q *Queries) SetSiteProxyPort(ctx context.Context, arg SetSiteProxyPortParams) error {
	_, err := q.db.Exec(ctx, setSiteProxyPort, arg.ID, arg.ProxyPort)
	return err
}

const setSiteStatus = `-- name: SetSiteStatus :exec
UPDATE sites
   SET provision_status = $2,
       updated_at       = now()
 WHERE id = $1
`

type SetSiteStatusParams struct {
	ID              int64
	ProvisionStatus string
}

func (q *Queries) SetSiteStatus(ctx context.Context, arg SetSiteStatusParams) error {
	_, err := q.db.Exec(ctx, setSiteStatus, arg.ID, arg.ProvisionStatus)
	return err
}

const setSiteWebhookSecret = `-- name: SetSiteWebhookSecret :exec
UPDATE sites
   SET webhook_secret = $2,
       updated_at     = now()
 WHERE id = $1
`

type SetSiteWebhookSecretParams struct {
	ID            int64
	WebhookSecret pgtype.Text
}

func (q *Queries) SetSiteWebhookSecret(ctx context.Context, arg SetSiteWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, setSiteWebhookSecret, arg.ID, arg.WebhookSecret)
	return err
}

const setSiteWorkingDir = `-- name: SetSiteWorkingDir :exec
UPDATE sites
   SET working_dir = $2,
       updated_at  = now()
 WHERE id = $1
`

type SetSiteWorkingDirParams struct {
	ID         int64
	WorkingDir string
}

func (q *Queries) SetSiteWorkingDir(ctx context.Context, arg SetSiteWorkingDirParams) error {
	_, err := q.db.Exec(ctx, setSiteWorkingDir, arg.ID, arg.WorkingDir)
	return err
}
