// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: site_permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSitePermission = `-- name: DeleteSitePermission :exec
DELETE FROM site_permissions WHERE id = $1 AND site_id = $2
`

type DeleteSitePermissionParams struct {
	ID     int64
	SiteID int64
}

func (q *Queries) DeleteSitePermission(ctx context.Context, arg DeleteSitePermissionParams) error {
	_, err := q.db.Exec(ctx, deleteSitePermission, arg.ID, arg.SiteID)
	return err
}

const listSitePermissions = `-- name: ListSitePermissions :many
SELECT id, site_id, user_id, team_id, perm_read, perm_execute, perm_write, perm_logs, perm_terminal, perm_inspect, created_at, updated_at FROM site_permissions WHERE site_id = $1 ORDER BY id
`

func (q *Queries) ListSitePermissions(ctx context.Context, siteID int64) ([]SitePermission, error) {
	rows, err := q.db.Query(ctx, listSitePermissions, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SitePermission
	for rows.Next() {
		var i SitePermission
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.UserID,
			&i.TeamID,
			&i.PermRead,
			&i.PermExecute,
			&i.PermWrite,
			&i.PermLogs,
			&i.PermTerminal,
			&i.PermInspect,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sitePermissionsForUser = `-- name: SitePermissionsForUser :one
SELECT
    COALESCE(BOOL_OR(perm_read),     false)::boolean AS perm_read,
    COALESCE(BOOL_OR(perm_execute),  false)::boolean AS perm_execute,
    COALESCE(BOOL_OR(perm_write),    false)::boolean AS perm_write,
    COALESCE(BOOL_OR(perm_logs),     false)::boolean AS perm_logs,
    COALESCE(BOOL_OR(perm_terminal), false)::boolean AS perm_terminal,
    COALESCE(BOOL_OR(perm_inspect),  false)::boolean AS perm_inspect
  FROM site_permissions sp
 WHERE sp.site_id = $1
   AND (
        sp.user_id = $2
        OR sp.team_id IN (SELECT team_id FROM team_members WHERE user_id = $2)
   )
`

type SitePermissionsForUserParams struct {
	SiteID int64
	UserID pgtype.Int8
}

type SitePermissionsForUserRow struct {
	PermRead     bool
	PermExecute  bool
	PermWrite    bool
	PermLogs     bool
	PermTerminal bool
	PermInspect  bool
}

// Returns the union of direct user perms + team-mediated perms a
// user holds for a site. Aggregated (OR-ed) at the SQL layer.
// BOOL_OR over zero rows yields NULL — COALESCE to false so the
// "no permissions" case comes back as an all-false row.
func (q *Queries) SitePermissionsForUser(ctx context.Context, arg SitePermissionsForUserParams) (SitePermissionsForUserRow, error) {
	row := q.db.QueryRow(ctx, sitePermissionsForUser, arg.SiteID, arg.UserID)
	var i SitePermissionsForUserRow
	err := row.Scan(
		&i.PermRead,
		&i.PermExecute,
		&i.PermWrite,
		&i.PermLogs,
		&i.PermTerminal,
		&i.PermInspect,
	)
	return i, err
}

const upsertSiteTeamPermission = `-- name: UpsertSiteTeamPermission :one
INSERT INTO site_permissions (
    site_id, team_id,
    perm_read, perm_execute, perm_write,
    perm_logs, perm_terminal, perm_inspect
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (site_id, team_id) WHERE team_id IS NOT NULL
DO UPDATE SET
    perm_read     = EXCLUDED.perm_read,
    perm_execute  = EXCLUDED.perm_execute,
    perm_write    = EXCLUDED.perm_write,
    perm_logs     = EXCLUDED.perm_logs,
    perm_terminal = EXCLUDED.perm_terminal,
    perm_inspect  = EXCLUDED.perm_inspect,
    updated_at    = now()
RETURNING id, site_id, user_id, team_id, perm_read, perm_execute, perm_write, perm_logs, perm_terminal, perm_inspect, created_at, updated_at
`

type UpsertSiteTeamPermissionParams struct {
	SiteID       int64
	TeamID       pgtype.Int8
	PermRead     bool
	PermExecute  bool
	PermWrite    bool
	PermLogs     bool
	PermTerminal bool
	PermInspect  bool
}

func (q *Queries) UpsertSiteTeamPermission(ctx context.Context, arg UpsertSiteTeamPermissionParams) (SitePermission, error) {
	row := q.db.QueryRow(ctx, upsertSiteTeamPermission,
		arg.SiteID,
		arg.TeamID,
		arg.PermRead,
		arg.PermExecute,
		arg.PermWrite,
		arg.PermLogs,
		arg.PermTerminal,
		arg.PermInspect,
	)
	var i SitePermission
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.UserID,
		&i.TeamID,
		&i.PermRead,
		&i.PermExecute,
		&i.PermWrite,
		&i.PermLogs,
		&i.PermTerminal,
		&i.PermInspect,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSiteUserPermission = `-- name: UpsertSiteUserPermission :one
INSERT INTO site_permissions (
    site_id, user_id,
    perm_read, perm_execute, perm_write,
    perm_logs, perm_terminal, perm_inspect
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (site_id, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET
    perm_read     = EXCLUDED.perm_read,
    perm_execute  = EXCLUDED.perm_execute,
    perm_write    = EXCLUDED.perm_write,
    perm_logs     = EXCLUDED.perm_logs,
    perm_terminal = EXCLUDED.perm_terminal,
    perm_inspect  = EXCLUDED.perm_inspect,
    updated_at    = now()
RETURNING id, site_id, user_id, team_id, perm_read, perm_execute, perm_write, perm_logs, perm_terminal, perm_inspect, created_at, updated_at
`

type UpsertSiteUserPermissionParams struct {
	SiteID       int64
	UserID       pgtype.Int8
	PermRead     bool
	PermExecute  bool
	PermWrite    bool
	PermLogs     bool
	PermTerminal bool
	PermInspect  bool
}

func (q *Queries) UpsertSiteUserPermission(ctx context.Context, arg UpsertSiteUserPermissionParams) (SitePermission, error) {
	row := q.db.QueryRow(ctx, upsertSiteUserPermission,
		arg.SiteID,
		arg.UserID,
		arg.PermRead,
		arg.PermExecute,
		arg.PermWrite,
		arg.PermLogs,
		arg.PermTerminal,
		arg.PermInspect,
	)
	var i SitePermission
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.UserID,
		&i.TeamID,
		&i.PermRead,
		&i.PermExecute,
		&i.PermWrite,
		&i.PermLogs,
		&i.PermTerminal,
		&i.PermInspect,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
