// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, enabled, mfa_secret, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         string
	Enabled      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Enabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, enabled, mfa_secret, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, enabled, mfa_secret, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, enabled, mfa_secret, created_at, updated_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Enabled,
			&i.MfaSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserEnabled = `-- name: SetUserEnabled :exec
UPDATE users
   SET enabled    = $2,
       updated_at = now()
 WHERE id = $1
`

type SetUserEnabledParams struct {
	ID      int64
	Enabled bool
}

func (q *Queries) SetUserEnabled(ctx context.Context, arg SetUserEnabledParams) error {
	_, err := q.db.Exec(ctx, setUserEnabled, arg.ID, arg.Enabled)
	return err
}

const setUserMFASecret = `-- name: SetUserMFASecret :exec
UPDATE users
   SET mfa_secret = $2,
       updated_at = now()
 WHERE id = $1
`

type SetUserMFASecretParams struct {
	ID        int64
	MfaSecret pgtype.Text
}

func (q *Queries) SetUserMFASecret(ctx context.Context, arg SetUserMFASecretParams) error {
	_, err := q.db.Exec(ctx, setUserMFASecret, arg.ID, arg.MfaSecret)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
   SET password_hash = $2,
       updated_at    = now()
 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
