/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedSitesIndexRouteImport } from './routes/_authenticated/sites/index'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedSitesNewRouteImport } from './routes/_authenticated/sites/new'
import { Route as AuthenticatedSitesIdRouteImport } from './routes/_authenticated/sites/$id'
import { Route as AuthenticatedServersNewRouteImport } from './routes/_authenticated/servers/new'
import { Route as AuthenticatedServersIdRouteImport } from './routes/_authenticated/servers/$id'
import { Route as AuthenticatedDeploysDeployIdRouteImport } from './routes/_authenticated/deploys/$deployId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesIndexRoute = AuthenticatedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesNewRoute = AuthenticatedSitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesIdRoute = AuthenticatedSitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServersNewRoute = AuthenticatedServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServersIdRoute = AuthenticatedServersIdRouteImport.update({
  id: '/servers/$id',
  path: '/servers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeploysDeployIdRoute =
  AuthenticatedDeploysDeployIdRouteImport.update({
    id: '/deploys/$deployId',
    path: '/deploys/$deployId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/deploys/$deployId': typeof AuthenticatedDeploysDeployIdRoute
  '/servers/$id': typeof AuthenticatedServersIdRoute
  '/servers/new': typeof AuthenticatedServersNewRoute
  '/sites/$id': typeof AuthenticatedSitesIdRoute
  '/sites/new': typeof AuthenticatedSitesNewRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
  '/sites/': typeof AuthenticatedSitesIndexRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/deploys/$deployId': typeof AuthenticatedDeploysDeployIdRoute
  '/servers/$id': typeof AuthenticatedServersIdRoute
  '/servers/new': typeof AuthenticatedServersNewRoute
  '/sites/$id': typeof AuthenticatedSitesIdRoute
  '/sites/new': typeof AuthenticatedSitesNewRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/sites': typeof AuthenticatedSitesIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/deploys/$deployId': typeof AuthenticatedDeploysDeployIdRoute
  '/_authenticated/servers/$id': typeof AuthenticatedServersIdRoute
  '/_authenticated/servers/new': typeof AuthenticatedServersNewRoute
  '/_authenticated/sites/$id': typeof AuthenticatedSitesIdRoute
  '/_authenticated/sites/new': typeof AuthenticatedSitesNewRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
  '/_authenticated/sites/': typeof AuthenticatedSitesIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/deploys/$deployId'
    | '/servers/$id'
    | '/servers/new'
    | '/sites/$id'
    | '/sites/new'
    | '/servers/'
    | '/sites/'
    | '/teams/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/deploys/$deployId'
    | '/servers/$id'
    | '/servers/new'
    | '/sites/$id'
    | '/sites/new'
    | '/servers'
    | '/sites'
    | '/teams'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/'
    | '/_authenticated/deploys/$deployId'
    | '/_authenticated/servers/$id'
    | '/_authenticated/servers/new'
    | '/_authenticated/sites/$id'
    | '/_authenticated/sites/new'
    | '/_authenticated/servers/'
    | '/_authenticated/sites/'
    | '/_authenticated/teams/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/': {
      id: '/_authenticated/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthenticatedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/new': {
      id: '/_authenticated/sites/new'
      path: '/sites/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof AuthenticatedSitesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$id': {
      id: '/_authenticated/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof AuthenticatedSitesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servers/new': {
      id: '/_authenticated/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof AuthenticatedServersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servers/$id': {
      id: '/_authenticated/servers/$id'
      path: '/servers/$id'
      fullPath: '/servers/$id'
      preLoaderRoute: typeof AuthenticatedServersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deploys/$deployId': {
      id: '/_authenticated/deploys/$deployId'
      path: '/deploys/$deployId'
      fullPath: '/deploys/$deployId'
      preLoaderRoute: typeof AuthenticatedDeploysDeployIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDeploysDeployIdRoute: typeof AuthenticatedDeploysDeployIdRoute
  AuthenticatedServersIdRoute: typeof AuthenticatedServersIdRoute
  AuthenticatedServersNewRoute: typeof AuthenticatedServersNewRoute
  AuthenticatedSitesIdRoute: typeof AuthenticatedSitesIdRoute
  AuthenticatedSitesNewRoute: typeof AuthenticatedSitesNewRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
  AuthenticatedSitesIndexRoute: typeof AuthenticatedSitesIndexRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDeploysDeployIdRoute: AuthenticatedDeploysDeployIdRoute,
  AuthenticatedServersIdRoute: AuthenticatedServersIdRoute,
  AuthenticatedServersNewRoute: AuthenticatedServersNewRoute,
  AuthenticatedSitesIdRoute: AuthenticatedSitesIdRoute,
  AuthenticatedSitesNewRoute: AuthenticatedSitesNewRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
  AuthenticatedSitesIndexRoute: AuthenticatedSitesIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
